name: vola_flutter
description: A new Flutter project with Serverpod.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  serverpod_flutter: 1.2.6
  vola_client:
    path: ../vola_client

  flutter_localizations:
    sdk: flutter

  # Communication withd server
  serverpod_auth_email_flutter: 1.2.6
  serverpod_auth_shared_flutter: 1.2.6

  # App spezific needs
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  intl: ^0.18.1
  iconsax_plus: ^1.0.0
  easy_localization: ^3.0.6
  dash_flags: ^0.1.1
  easy_container: ^1.0.4+1
  simple_shadow: ^0.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/translations/
